[package]
name = "blockkey-prototype"
version = "0.1.0"
authors = ["Miles Watson <contact@mileswatson.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = {version = "0.37.1", features = ["tcp-tokio"] }
futures = "0.3.15"
tokio = { version="1.6.0", features = ["full"] }
